### ISSUE TITLE
Let chatbot send messages at specific timepoints

### ISSUE THREAD

**Issue by sakritz** [ebeneditos/telegram.bot#15]
Hi, 

I am trying to get my chatbot to send messages at specific timepoints (right now, I'd be happy to sent these timepoint while programming, e.g., make the chatbot send "It's a new hour!" at each full hour; eventually, I'd need randomly chosen timepoints). 

Is there a way to do this? 
If so, could you give me a minimal example?

Thanks!
Sarah

**Comment by krose** [comment]
Hi

I send messages to a group like below. You can use a cron job to run this script:

```
library(telegram.bot)

telegram_pat <- "<your-token>"
chat_id <- "<telegram-chat-id>"

bot <- Bot(token = telegram_pat)
  
  bot$sendMessage(
    chat_id = chat_id,
    text = "Your message",
    parse_mode = "Markdown"
  )

```

**Comment by GreyMerchant** [comment]
Hello :) I saw this post and wanted to ask a related question. Telegram added a feature a while ago to do a delayed message. Is there some way to send all of them and get them handled appropriately with the intended delay?

**Comment by ebeneditos** [comment]
Closing as initial issue was solved, @GreyMerchant please feel free to open a new one with your suggestion.
