### ISSUE TITLE
HTTP 403 Error

### ISSUE THREAD

**Issue by tolgakurtuluss** [ebeneditos/telegram.bot#19]
Hello everyone!

I was using my basic level bot with telegram.bot library but it started to give this error as given below.
I tried to revoke API but didn't work for me.

> updater$start_polling()
Error in private$request(url, data) : Forbidden (HTTP 403).
Called from: httr::stop_for_status(result)
Browse[1]>

**Comment by ebeneditos** [comment]
Hi, could you please share a replicable example to see when that happens? Thanks!

**Comment by ebeneditos** [comment]
I do not get this error with that same code, did you start the bot from Telegram?
Try going to this URL https://api.telegram.org/bot{yourtoken}/get_me replacing your token, if it does not work it's either your token or registration that is not correct.

**Comment by tolgakurtuluss** [comment]
Thank you for your support. Errors no longer appear when I am running the code.

**Comment by hfahmy** [comment]
This error will appear if the user block the bot. Is there any way to catch the error @ebeneditos ?
