### ISSUE TITLE
forwardMessage not included in bot methods

### ISSUE THREAD

**Issue by mabafaba** [ebeneditos/telegram.bot#21]
I was trying to forward messages, but `bot$forwardMessage` seems to be empty.
Was looking into it, and it seems the function is not named here:
https://github.com/ebeneditos/telegram.bot/blob/43ffa04cc14889e8d412cb6b7476ebe85574fab1/R/bot.R#L1704
might very well be a mistake on my end though.
Thanks for checking!
m

**Comment by mabafaba** [comment]
cloded the pull request i made because i did it from the master branch sorry

**Comment by ebeneditos** [comment]
Hi @mabafaba, thanks for pointing out, I will update it this week, by next week it should be updated in CRAN

**Comment by mabafaba** [comment]
<3 thanks

**Comment by ebeneditos** [comment]
Looks good, just accepted the pull request and will send it to CRAN during the week, thanks for the work!
