### ISSUE TITLE
Russian language tutorial for work with telegram.bot package

### ISSUE THREAD

**Issue by selesnow** [ebeneditos/telegram.bot#25]
Hello, thanks for telegram.bot.

I am wrote russian language tutorial for russian language package users.

- [Разработка telegram ботов на языке R](https://selesnow.github.io/build_telegram_bot_using_r/)

**Comment by ebeneditos** [comment]
Hi @selesnow, thanks for the effort.
Since this is not an issue on the package performance, I will proceed to close it.
