### ISSUE TITLE
How to host telegram.bot using Google Cloud Platform or Heroku

### ISSUE THREAD

**Issue by selesnow** [ebeneditos/telegram.bot#26]
Hello, 

I think a vignette for deploying bots on cloud platforms would be useful to for many telegram.bot users.

**Comment by ebeneditos** [comment]
Hi @selesnow, thanks for the suggestion.
The core of telegram.bot is to provide a number of tools to make the development of Telegram bots with R easy and straightforward. Deploying a Telegram bot on the cloud would be a project beyond its core, although the package can be used to do so.
