### ISSUE TITLE
Color code caption bot$sendPhoto

### ISSUE THREAD

**Issue by HugoGit39** [ebeneditos/telegram.bot#37]
Hi,

I try to add a caption with a colorcoded word. But it only applies strong to the word. Would be great if a color is possible!

```
  bot$sendPhoto(chat_id = xxx, 
                caption = paste0("This is an ", strong("example", style="color:#44AA99"), 
                photo = "Example.png",
                parse_mode = "HTML")
```

**Comment by ebeneditos** [comment]
This functionality is not developed yet, guess this is more a suggestion than an issue, thanks for the comment!
