### ISSUE TITLE
Feature request  · sendPoll

### ISSUE THREAD

**Issue by walmes** [ebeneditos/telegram.bot#38]
Greetings @ebeneditos,

I would like to start by congratulating you on the excellent package. Your package has enabled me to redirect diagnostics from my Shiny applications and other deployed projects based on R using Telegram. I now have a more detailed tracking of how these applications perform, which has significantly improved the quality and monitoring of what I deliver.

As a professor, I am now considering expanding the use of Telegram for quick quizzes with my students. I am interested in implementing adaptive assessments, where based on a student’s correct or incorrect answers, they are given questions of an appropriate difficulty level.  However, to achieve this, I would need the `sendPoll()` method to create multiple-choice questions, either anonymous or not, and for quick surveys. These polls can have images, like data charts (histogramns, bar charts), and also output of models. Telegram can deliver an interesting environment to students learn and we can use LLM to give feedback on the answers. This feature would be an amazing contribution.

Is there any plan to implement this feature? It would be extremely helpful. Thank you again for the great work you’ve done.

Best regards,
Walmes.

**Comment by ebeneditos** [comment]
Hi Walmes, thanks a lot for the message. Unfortunately there is not plan on upcoming updates due to capacity constraints (unless some contributor does it). Glad you still find it useful.
