### ISSUE TITLE
editMessageReplyMarkup not working with reply_markup (InlineKeyboardMarkup)

### ISSUE THREAD

**Issue by dtaytson** [ebeneditos/telegram.bot#9]
I tryed to run this code with editMessageReplyMarkup and failed with "Unsupported value type for form field"

`## Not run: 
# Initialize bot
bot <- Bot(token = "TOKEN")
chat_id <- "CHAT_ID"
message_id <- "MESSAGE ID"

# Create Inline Keyboard
text <- "Could you type their phone number, please?"
IKM <- InlineKeyboardMarkup(
  inline_keyboard = list(
    list(InlineKeyboardButton(1),
         InlineKeyboardButton(2),
         InlineKeyboardButton(3)),
    list(InlineKeyboardButton(4),
         InlineKeyboardButton(5),
         InlineKeyboardButton(6)),
    list(InlineKeyboardButton(7),
         InlineKeyboardButton(8),
         InlineKeyboardButton(9)),
    list(InlineKeyboardButton("*"),
         InlineKeyboardButton(0),
         InlineKeyboardButton("#"))
    )
  )

# Send Inline Keyboard
    bot$editMessageReplyMarkup(chat_id,
                               message_id, reply_markup = IKM)
## End(Not run)`

Error in curl::handle_setform(handle, .list = req$fields) :
  Unsupported value type for form field 'reply_markup'.
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> request_perform -> <Anonymous>
Execution halted

**Comment by ebeneditos** [comment]
There was a little bug. I reviewed the code and it only affects to `editMessageReplyMarkup`.
It is solved in the development version, within the next days it will be updated on CRAN.

Thanks for the report!
